server:
  port: 10003
spring:
  application:
    name: hi-cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      loadbalancer:
        use404: true
    nacos:
      discovery:
        server-addr: localhost:8848

logging:
  level:
    org.springframework:cloud.gateway: debug