#server:
#  port: 10003
#spring:
#  application:
#    name: hi-cloud-gateway
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#      loadbalancer:
#        use404: true
#    nacos:
#      discovery:
#        server-addr: 173.249.38.245:8848
#
#logging:
#  level:
#    org.springframework:cloud.gateway: debug